### ISSUE TITLE
Enabling system cursor disables 3D from rendering

### ISSUE THREAD

**Issue by NB-NutBoi** [lunarcleint/3D-HaxeFlixel#3]
unsure of why it happens, i looked and i can't pinpoint the issue, but disabling the flixel cursor in any way (including but not limited to FlxG.mouse.useSystemCursor = true) seems to completely disable FlxView3D from rendering

**Comment by lunarcleint** [comment]
Can you add me on discord so we can debug the problem better? 
lunarcleint#8859
